In [1]:
#Q1 Create a NumPy array containing integers from 0 to 9.
import numpy as np
arr = np.array(10)
print(arr)

10


In [2]:
#Q2Create a NumPy array from a given Python list [10, 20, 30, 40, 50].
import numpy as np

my_list = [10, 20, 30, 40, 50]
arr = np.array(my_list)

print(arr)

[10 20 30 40 50]


In [3]:
#Q3 Create a 2D array (3x3) with values ranging from 0 to 8.
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#Q4 Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.
import numpy as np

arr = np.random.randint(1, 101, size=(5, 4))

print("Array:\n", arr)

print("Shape:", arr.shape)   
print("Size:", arr.size)     
import numpy as np

arr = np.random.randint(1, 101, size=(5, 4))

print("Array:\n", arr)

print("Shape:", arr.shape)   
print("Size:", arr.size)     


Array:
 [[ 3 55 28 38]
 [48 61 26 76]
 [83 61 74 96]
 [58 88  4 34]
 [94 60 53  1]]
Shape: (5, 4)
Size: 20
Array:
 [[86 85 54  9]
 [93 89 33 17]
 [33 13 34 72]
 [41 63 98 27]
 [68 32 44 17]]
Shape: (5, 4)
Size: 20


In [5]:
#Q5 Create a 3x3 array of integers and access:
#a. The second element of the first row.
#b. The third column of the 2nd row.
#c. A subarray with the first two rows and last two columns.
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Array:\n", arr)

print("a:", arr[0, 1])

print("b:", arr[1, 2])

print("c:\n", arr[0:2, 1:3])


Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
a: 20
b: 60
c:
 [[20 30]
 [50 60]]


In [6]:
#Q6 Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.
import numpy as np

arr = np.arange(12)

reshaped_arr = arr.reshape(3, 4)

print("Original 1D Array:", arr)
print("Reshaped 3x4 Array:\n", reshaped_arr)


Original 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
#Q7 Reshape a 3x3 matrix into a 1D array.
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

flat_arr = arr.reshape(-1)

print("Original 3x3 Matrix:\n", arr)
print("Reshaped 1D Array:", flat_arr)


Original 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped 1D Array: [1 2 3 4 5 6 7 8 9]


In [8]:
#Q8 Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,subtraction, multiplication, and division on them.
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[6, 5, 4],
                 [3, 2, 1]])

print("arr1:\n", arr1)
print("arr2:\n", arr2)

print("\nAddition:\n", arr1 + arr2)
print("\nSubtraction:\n", arr1 - arr2)
print("\nMultiplication:\n", arr1 * arr2)
print("\nDivision:\n", arr1 / arr2)


arr1:
 [[1 2 3]
 [4 5 6]]
arr2:
 [[6 5 4]
 [3 2 1]]

Addition:
 [[7 7 7]
 [7 7 7]]

Subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]

Multiplication:
 [[ 6 10 12]
 [12 10  6]]

Division:
 [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


In [9]:
#Q9 Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

total_sum = np.sum(arr)
mean_value = np.mean(arr)
std_deviation = np.std(arr)

print("Array:", arr)
print("Sum:", total_sum)
print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)


Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Standard Deviation: 14.142135623730951


In [10]:
#Q10 Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

result_dot = np.dot(A, B)

result_at = A @ B

print("\nMatrix Multiplication using np.dot():\n", result_dot)
print("\nMatrix Multiplication using @ operator:\n", result_at)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Matrix Multiplication using np.dot():
 [[19 22]
 [43 50]]

Matrix Multiplication using @ operator:
 [[19 22]
 [43 50]]


In [11]:
#Q11 Find the transpose of matrix A and matrix B.
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A_T = A.T
B_T = B.T

print("Matrix A:\n", A)
print("Transpose of A:\n", A_T)

print("\nMatrix B:\n", B)
print("Transpose of B:\n", B_T)



Matrix A:
 [[1 2]
 [3 4]]
Transpose of A:
 [[1 3]
 [2 4]]

Matrix B:
 [[5 6]
 [7 8]]
Transpose of B:
 [[5 7]
 [6 8]]


In [12]:
#Q12 Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.
import numpy as np

arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr1d = np.array([10, 20, 30])
result = arr2d + arr1d

print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [13]:

#Q13 Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.
import numpy as np

arr = np.random.randint(1, 100, (4, 4))

print("Array:")
print(arr)

max_val = arr.max()

min_val = arr.min()

mean_val = arr.mean()

print("\nMaximum:", max_val)
print("Minimum:", min_val)
print("Mean:", mean_val)


Array:
[[95 60 35 40]
 [ 3 20 45 15]
 [17 77 24 15]
 [36 66  6 92]]

Maximum: 95
Minimum: 3
Mean: 40.375


In [14]:
#Q14 Find the row-wise and column-wise sums
import numpy as np

arr = np.random.randint(1, 100, (4, 4))
print("Array:")
print(arr)


Array:
[[34 60 22 23]
 [42 24  3 69]
 [ 8 57 82 96]
 [83 93 56 84]]


In [15]:
#Q15 Generate an array of 10 random integers between 1 and 50.
import numpy as np

arr = np.random.randint(1, 51, 10)
print(arr)


[ 2  7 29 44 20  3  3 24 25 42]


In [16]:
#Q16 Generate a 5x5 matrix of random floats between 0 and 1.
import numpy as np

matrix = np.random.rand(5, 5)
print(matrix)


[[0.02490196 0.92939904 0.72986016 0.21879276 0.31188457]
 [0.70274813 0.80756144 0.48809763 0.4030238  0.17044499]
 [0.10396397 0.17080634 0.53564235 0.90550693 0.92802086]
 [0.31326776 0.99693697 0.4834812  0.52817075 0.42706982]
 [0.28068697 0.26670056 0.40163625 0.207177   0.28574981]]
