In [1]:
##Numpy

#Q1 Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [2]:
import numpy as np

In [3]:
matrix = np.arange(2, 14).reshape(4, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [4]:
#Q2 Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [5]:
import numpy as np

In [6]:
arr = np.random.randint(1,50,20)

In [7]:
print("Original Array:",arr)

Original Array: [38 20  4 49 15 41 12 30 24 23 25 18  6  8  4  6 47 41 14  5]


In [9]:
arr[arr % 2 != 0] = -1

In [11]:
print("\nUpdated Array:",arr)


Updated Array: [38 20  4 -1 -1 -1 12 30 24 -1 -1 18  6  8  4  6 -1 -1 14 -1]


In [14]:
#Q3 Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.

In [15]:
import numpy as np

In [17]:
# a. Create a 1D-array of mobile phone prices
prices = np.array([6999,7500,11999,27899,14999,9999])
print("Oringinal Prices:",prices)

Oringinal Prices: [ 6999  7500 11999 27899 14999  9999]


In [18]:
# b. Convert this array to float type
prices = prices.astype(float)
print("Float Prices:",prices)

Float Prices: [ 6999.  7500. 11999. 27899. 14999.  9999.]


In [19]:
# c. Append a new mobile having price of 13999
prices = np.append(prices, 13999)
print("After Appending 13999:", prices)

After Appending 13999: [ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]


In [21]:
# d. Reverse this array
prices = prices[::-1]
print("Reversed Prices:", prices)

Reversed Prices: [ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]


In [29]:
# e. Apply GST of 18% and update
prices = prices * 1.18
print("After Applying 18% GST:", prices)

After Applying 18% GST: [ 26308.25555949  28191.44402003  45102.55157284 104868.41289531
  56379.12918086  37584.8331675   52620.26997819]


In [33]:
# f. Sort array in descending order
prices_desc = np.sort(prices)[::-1]
print("Sorted (Descending):", prices_desc)

Sorted (Descending): [104868.41289531  56379.12918086  52620.26997819  45102.55157284
  37584.8331675   28191.44402003  26308.25555949]


In [34]:
# g. Average mobile phone price
average_price = np.mean(prices)
print("Average Price:", average_price)

Average Price: 50150.699482031356


In [35]:
# h. Difference between max and min price
difference = np.max(prices) - np.min(prices)
print("Difference (Max - Min):", difference)

Difference (Max - Min): 78560.15733581586


In [1]:
#Q4 Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)
